### PR TITLE
set spark session timeout

### PR DESCRIPTION
**Pull request by Tianhao-Gu**
auto stop spark session to prevent idle session from consuming all resources 
Screenshot 2024-05-31 at 1 26 48 PM

### CODE REVIEW

**Comment by MrCreosote** [comment]
So your session is killed 24h after you created it, no matter what?

**Comment by Tianhao-Gu** [comment]
> So your session is killed 24h after you created it, no matter what?

after 4 hours. I don't anticipate anyone will use spark session longer than that. I noticed people don't stop spark session properly. We need to enforce closing sessions. As the screenshot shows, currently there is an open spark session running for 24 hours taking all resources.

**Comment by MrCreosote** [comment]
> after 4 hours. 

oops

**Review by MrCreosote — APPROVED** [review]
This seems ok as a temporary measure, but I can see cases where people might be doing complicated computations / work and have legit sessions take > 4h. We probably need to figure out a better solution long term - maybe bring this up in the checkpoint next week?

**Comment by Tianhao-Gu** [comment]
> This seems ok as a temporary measure, but I can see cases where people might be doing complicated computations / work and have legit sessions take > 4h. We probably need to figure out a better solution long term - maybe bring this up in the checkpoint next week?

how about making timeout_seconds as an argument to the function. So that if people want a longer session, they can specify it during func calls.

**Comment by MrCreosote** [comment]
That also seems fine for now, but long term I'm not sure it'll work, hence discussion next week

**Pull request merged**
