### PR TITLE
add bashrc ext files

### PR DESCRIPTION
**Pull request by Tianhao-Gu**

### CODE REVIEW

**Comment by MrCreosote** [comment]
Why the .ext file extensions? Is it something to do with this? https://docs.nersc.gov/environment/#dotfiles-and-customizing-your-environment

**Comment by Tianhao-Gu** [comment]
> Why the .ext file extensions? Is it something to do with this? https://docs.nersc.gov/environment/#dotfiles-and-customizing-your-environment

yea. I copied the implementation idea from NERSC. But we could change the `.ext` to something our own. Our use case currently is much simpler. I will basically just use them as template files and create .bashrc and .bash_profile in users' home dir.

**Comment by MrCreosote** [comment]
Why have extensions at all then?

**Comment by Tianhao-Gu** [comment]
> Why have extensions at all then?

To keep them different from `.bashrc` and `.bash_profile`. It's just a file extension that only makes sense to us and NERSC once had it too so I borrowed it.

**Comment by MrCreosote** [comment]
If you're using them as a template and making the actual files in the user home dir why do the have to have different file names?

**Comment by Tianhao-Gu** [comment]
> If you're using them as a template and making the actual files in the user home dir why do the have to have different file names?

They don't have to be. They're just placeholders. Can you suggest you preferred file names for this PR approval? And I'll just update them accordingly.

**Comment by MrCreosote** [comment]
I would either do no extention at all, or if you expect them to be jinja templates or something, `.tmpl`

**Comment by Tianhao-Gu** [comment]
> I would either do no extension at all, or if you expect them to be jinja templates or something, `.tmpl`

👍

**Review by MrCreosote — APPROVED** [review]

**Pull request merged**
