### PR TITLE
set dynamic allocation for parallel jobs

### PR DESCRIPTION
**Pull request by Tianhao-Gu**
Screenshot 2024-05-30 at 11 43 32 AM

### CODE REVIEW

**Comment by MrCreosote** [comment]
Can you explain the purpose of this change? When I was running example jobs against spark they were using both workers without config so I'm wondering what this does

**Comment by Tianhao-Gu** [comment]
> Can you explain the purpose of this change? When I was running example jobs against spark they were using both workers without config so I'm wondering what this does

it allows parallel job executions. I commented on it in the notebook bash script.

**Comment by MrCreosote** [comment]
What happens if 2 people in 2 different notebooks run jobs?

**Comment by Tianhao-Gu** [comment]
> What happens if 2 people in 2 different notebooks run jobs?

It should allow both jobs running.

**Comment by MrCreosote** [comment]
> It should allow both jobs running.

Are the changes here needed for that, or are they just to allow parallel jobs to run from a single notebook?

**Comment by Tianhao-Gu** [comment]
> > It should allow both jobs running.
> 
> Are the changes here needed for that, or are they just to allow parallel jobs to run from a single notebook?

Currently job execution is FIFO meaning any job will take all resources and all other jobs will be waiting.

**Comment by MrCreosote** [comment]
Ok, so what happens if one notebook has parallel executors configured and the other doesn't and they both submit jobs?

**Comment by Tianhao-Gu** [comment]
> Ok, so what happens if one notebook has parallel executors configured and the other doesn't and they both submit jobs?

I don’t know why it matters. Our cluster only has one notebook.

**Comment by MrCreosote** [comment]
For now. I'm trying to understand how this works - it seems odd to me that the configuration is on the "client" rather than on the cluster itself

**Comment by MrCreosote** [comment]
Ok, so back to the original question - what happens if 2 drivers request resources from the manager, and one has these settings and the other doesn't?

**Comment by Tianhao-Gu** [comment]
> Ok, so back to the original question - what happens if 2 drivers request resources from the manager, and one has these settings and the other doesn't?

My best guess is if driver without this setting submit job first, it will take all resources same as of now. And driver with this setting will wait for the first job to finish. I didn't get your cornering regarding this. This is the easiest way to allow parallel jobs with our current stand alone setting.

**Comment by MrCreosote** [comment]
> I didn't get your cornering regarding this.

Not understanding you here

**Comment by Tianhao-Gu** [comment]
> > I didn't get your cornering regarding this.
> 
> Not understanding you here

^concerns

**Comment by MrCreosote** [comment]
It's less concerns and more understanding how the settings work and what the implications are for the future when we presumably will have multiple notebooks running against the cluster simultaneously, and maybe even people firing up their own notebooks with their own settings in a BYOC scenario

**Review by MrCreosote — APPROVED** [review]
This is another one that seems fine for now but might need rethinking longer term

**Pull request merged**
